version: '2'
services:
    gateway-app:
        image: gateway
        external_links:
            - gateway-postgresql:postgresql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/gateway
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - JHIPSTER_SLEEP=30
        ports:
            - 8080:8080
    gateway-postgresql:
        container_name: gateway-postgresql
        image: postgres:9.5.4
        environment:
            - POSTGRES_USER=gateway
            - POSTGRES_PASSWORD=
    
    todo-app:
        image: todo
        external_links:
            - todo-mongodb:mongodb
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=todo
            - JHIPSTER_SLEEP=10
    todo-mongodb:
        container_name: todo-mongodb
        image: mongo:3.3.12
    
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry

