#common configuration shared between all applications
configserver:
    name: Docker JHipster Registry
    status: Connected to the JHipster Registry running in Docker

jhipster:
    security:
        authentication:
            jwt:
                secret: 3a57edd09a70cffd3eeaabef2dd83b54ed30bc16

eureka:
    client:
        serviceUrl:
            defaultZone: http://admin:admin@registry:8761/eureka/
